### ISSUE TITLE
Unable to connect to ChromaDB running in Docker

### ISSUE THREAD

**Issue by sachinkumaranumula** [run-llama/create-llama#301]
I am running ChromaDB in a docker container which is reachable under http://localhost:8000 and I created shell app using `npx create-llama@latest` which gave me a nextJs app with `"llamaindex": "0.5.24"` dependency. I used a notebook to verify ChromaDB is reachable and it is where I am able to create collection and add documents to it. Can you please shed where the issue might be?

```
Start creating embeddings...
/Users/sachinkumaranumula/Workspace/let-loose-models/question-answer-on-url/node_modules/chromadb/dist/cjs/chromadb.cjs:2844
      throw new Error(newCollection.error);
            ^


Error: TypeError: fetch failed
    at ChromaClient.getOrCreateCollection (/Users/sachinkumaranumula/Workspace/let-loose-models/question-answer-on-url/node_modules/chromadb/dist/cjs/chromadb.cjs:2844:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async ChromaVectorStore.getCollection (/Users/sachinkumaranumula/Workspace/let-loose-models/question-answer-on-url/node_modules/llamaindex/dist/cjs/storage/vectorStore/ChromaVectorStore.js:34:26)
    at async ChromaVectorStore.add (/Users/sachinkumaranumula/Workspace/let-loose-models/question-answer-on-url/node_modules/llamaindex/dist/cjs/storage/vectorStore/ChromaVectorStore.js:55:28)
    at async addNodesToVectorStores (/Users/sachinkumaranumula/Workspace/let-loose-models/question-answer-on-url/node_modules/llamaindex/dist/cjs/ingestion/IngestionPipeline.js:113:28)
    at async VectorStoreIndex.insertNodes (/Users/sachinkumaranumula/Workspace/let-loose-models/question-answer-on-url/node_modules/llamaindex/dist/cjs/indices/vectorStore/index.js:574:9)
    at async VectorStoreIndex.buildIndexFromNodes (/Users/sachinkumaranumula/Workspace/let-loose-models/question-answer-on-url/node_modules/llamaindex/dist/cjs/indices/vectorStore/index.js:488:9)
    at async VectorStoreIndex.init (/Users/sachinkumaranumula/Workspace/let-loose-models/question-answer-on-url/node_modules/llamaindex/dist/cjs/indices/vectorStore/index.js:438:13)
    at async VectorStoreIndex.fromDocuments (/Users/sachinkumaranumula/Workspace/let-loose-models/question-answer-on-url/node_modules/llamaindex/dist/cjs/indices/vectorStore/index.js:516:16)
    at async loadAndIndex (/Users/sachinkumaranumula/Workspace/let-loose-models/question-answer-on-url/app/api/chat/engine/generate.ts:26:3)
    at async <anonymous> (/Users/sachinkumaranumula/Workspace/let-loose-models/question-answer-on-url/app/api/chat/engine/generate.ts:35:3)

Node.js v22.7.0
```

**Comment by marcusschiesser** [comment]
What are your settings in .env for the `CHROMA_*` variables?
