### ISSUE TITLE
extractText is not a function

### ISSUE THREAD

**Issue by Robing** [run-llama/create-llama#384]
When uploading a PDF file in the chat window, an error occurs stating 'extractText is not a function'.

> [Upload API] TypeError: extractText is not a function
    at readPDF (webpack-internal:///(rsc)/./node_modules/.pnpm/llamaindex@0.6.22_@aws-sdk+client-sso-oidc@3.670.0_@aws-sdk+client-sts@3.670.0__@aws-sdk+cred_4cqb3jcjwdzlpa5cxd3sxc2oxe/node_modules/llamaindex/dist/readers/PDFReader.js:30:18)
    at async PDFReader.loadDataAsContent (webpack-internal:///(rsc)/./node_modules/.pnpm/llamaindex@0.6.22_@aws-sdk+client-sso-oidc@3.670.0_@aws-sdk+client-sts@3.670.0__@aws-sdk+cred_4cqb3jcjwdzlpa5cxd3sxc2oxe/node_modules/llamaindex/dist/readers/PDFReader.js:15:38)
    at async loadDocuments (webpack-internal:///(rsc)/./app/api/chat/llamaindex/documents/helper.ts:67:12)
    at async parseFile (webpack-internal:///(rsc)/./app/api/chat/llamaindex/documents/helper.ts:50:23)
    at async uploadDocument (webpack-internal:///(rsc)/./app/api/chat/llamaindex/documents/upload.ts:54:23)
    at async POST (webpack-internal:///(rsc)/./app/api/chat/upload/route.ts:29:75)
    at async /Users/robin/mychat-pdf2/node_modules/.pnpm/next@14.2.15_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:55778
    at async eO.execute (/Users/robin/mychat-pdf2/node_modules/.pnpm/next@14.2.15_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:46527)
    at async eO.handle (/Users/robin/mychat-pdf2/node_modules/.pnpm/next@14.2.15_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:57112)
    at async doRender (/Users/robin/mychat-pdf2/node_modules/.pnpm/next@14.2.15_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1352:42)
    at async cacheEntry.responseCache.get.routeKind (/Users/robin/mychat-pdf2/node_modules/.pnpm/next@14.2.15_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1574:28)
    at async DevServer.renderToResponseWithComponentsImpl (/Users/robin/mychat-pdf2/node_modules/.pnpm/next@14.2.15_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1482:28)
    at async DevServer.renderPageComponent (/Users/robin/mychat-pdf2/node_modules/.pnpm/next@14.2.15_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1908:24)
    at async DevServer.renderToResponseImpl (/Users/robin/mychat-pdf2/node_modules/.pnpm/next@14.2.15_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1946:32)
    at async DevServer.pipeImpl (/Users/robin/mychat-pdf2/node_modules/.pnpm/next@14.2.15_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:921:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/robin/mychat-pdf2/node_modules/.pnpm/next@14.2.15_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/Users/robin/mychat-pdf2/node_modules/.pnpm/next@14.2.15_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:817:17)
    at async /Users/robin/mychat-pdf2/node_modules/.pnpm/next@14.2.15_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/robin/mychat-pdf2/node_modules/.pnpm/next@14.2.15_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Users/robin/mychat-pdf2/node_modules/.pnpm/next@14.2.15_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Users/robin/mychat-pdf2/node_modules/.pnpm/next@14.2.15_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:173:21)
    at async handleRequest (/Users/robin/mychat-pdf2/node_modules/.pnpm/next@14.2.15_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:350:24)
    at async requestHandlerImpl (/Users/robin/mychat-pdf2/node_modules/.pnpm/next@14.2.15_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:374:13)
    at async Server.requestListener (/Users/robin/mychat-pdf2/node_modules/.pnpm/next@14.2.15_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/start-server.js:141:13)

**Comment by marcusschiesser** [comment]
@leehuwuj that might be related to our refactoring?

**Comment by Robing** [comment]
![image](https://github.com/user-attachments/assets/7937fc14-5cc6-4f5a-a583-bca7a085873e)
@leehuwuj @marcusschiesser  This issue might be related to package building. The unpdf module seems to be ignored after the build process.

**Comment by marcusschiesser** [comment]
@himself65 as we upgraded LITS - anything that got changed there?

**Comment by himself65** [comment]
It might be a regression, i should re-export it in index.edge.ts in llamaindex package

**Comment by marcusschiesser** [comment]
@himself65 it's a different error, it's not about `extractText` from LITS but from unpdf.
https://github.com/run-llama/LlamaIndexTS/pull/1369 fixes this error - I keep this ticket open, until we update create-llama

**Comment by marcusschiesser** [comment]
we need to update to LITS 0.7.5 or later

**Comment by himself65** [comment]
Forget to update, I tried to only use `unpdf` in next.js. it's suprusing that it's empty `{}`! I have no idea why for now

**Comment by himself65** [comment]
I'm guessint we need bump next.js to 15?

**Comment by marcusschiesser** [comment]
@himself65 yes, that's part of https://github.com/run-llama/create-llama/issues/345

**Comment by marcusschiesser** [comment]
@Robing should be fixed in 0.3.9 - please retest
