### ISSUE TITLE
LlamaPack not working with 0.1.0

### ISSUE THREAD

**Issue by leegang** [run-llama/create-llama#69]
```
npx create-llama@latest
✔ What is your project named? … my-app
✔ Which template would you like to use? › Example using a LlamaPack
✔ Select LlamaPack › rag-fusion-query-pipeline

Aborting installation.
Unexpected error. Please report it as a bug:
 TypeError: Cannot read properties of undefined (reading 'provider')
    at isModelConfigured (/Users/leegang/.npm/_npx/7bfc2205dda2d438/node_modules/create-llama/dist/index.js:298:55245)
    at askPostInstallAction (/Users/leegang/.npm/_npx/7bfc2205dda2d438/node_modules/create-llama/dist/index.js:298:16399)
    at askQuestions (/Users/leegang/.npm/_npx/7bfc2205dda2d438/node_modules/create-llama/dist/index.js:298:17907)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (/Users/leegang/.npm/_npx/7bfc2205dda2d438/node_modules/create-llama/dist/index.js:298:72553)
```

**Comment by marcusschiesser** [comment]
@leegang Thanks for finding this issue. We'll fix that for the next release. Meanwhile please use `npx create-llama@0.0.32` for LlamaPacks
